import axiosClient from './axiosClient'

/**
 * Submit a new character generation task to Meshy.ai via backend.
 * @param {string} prompt - Text description of the character
 * @param {string} artStyle - Art style (cartoon, low-poly, realistic, anime, voxel)
 * @param {string} characterName - Optional friendly name
 */
export const generateCharacter = async (prompt, artStyle, characterName = 'My Buddy') => {
  const response = await axiosClient.post('/character/generate', {
    prompt,
    artStyle,
    characterName,
  })
  return response.data.data
}

/**
 * Poll the status of a character generation task.
 * @param {number} characterId - The DB id of the character task
 */
export const getCharacterTaskStatus = async (characterId) => {
  const response = await axiosClient.get(`/character/task/${characterId}`)
  return response.data.data
}

/**
 * Get all characters generated by the current user.
 */
export const getMyCharacters = async () => {
  const response = await axiosClient.get('/character/my-characters')
  return response.data.data
}
